### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by hirokik0811** [hirokik0811/EC463_miniproject#9]
# Issue
We should work with the same (or at least similar) environment to avoid any conflictions when building the project.

# Possible Solution
Some toolchains for building a React project are given https://reactjs.org/docs/create-a-new-react-app.html#create-react-app :

Recommended Toolchains
The React team primarily recommends these solutions:

If you’re learning React or creating a new single-page app, use Create React App.
If you’re building a server-rendered website with Node.js, try Next.js.
If you’re building a static content-oriented website, try Gatsby.
If you’re building a component library or integrating with an existing codebase, try More Flexible Toolchains.

Since we need the SSO login and have to implement multiple features, Create React App is probably too simple. 
I think Next.js is the best option for us.

**Comment by zb8787** [comment]
Ok will pursue next.js implementation - good thinking to not clash environments..

**Comment by zb8787** [comment]
Another possible web framework is Express.js
It is good for creating and running a web server with node, and we can also implement SSO using this scheme.
[https://expressjs.com/en/starter/installing.html](url)

**Comment by hirokik0811** [comment]
Django is chosen.
